LunarLander:
  env: LunarLander-v3
  gamma: 0.99
  replay_buffer_size: 100000
  batch_size: 32
  epsilon_initial: 1.0
  epsilon_decay: 0.995
  epsilon_min: 0.05
  learning_rate: 0.00025
  network_sync_rate: 10
  replay_ratio: 4